### ISSUE TITLE
Fail to enable Ingress in minekube  v1.25.2 

### ISSUE THREAD

**Issue by magichan** [dragonflyoss/helm-charts#68]
## Env
```
± % minikube version    --components                                                                                                  !9103
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7

buildctl:
buildctl github.com/moby/buildkit v0.9.3 8d2625494a6a3d413e3d875a2ff7dd9b1ed1b1a9

containerd:
containerd containerd.io 1.4.12 7b11cfaabd73bb80907dd23182b9347b4245eb5d

crictl:
crictl version v1.21.0

crio:
crio version 1.22.1

crun:
crun version UNKNOWN

ctr:
ctr containerd.io 1.4.12

docker:
Docker version 20.10.12, build e91ed57

dockerd:
Docker version 20.10.12, build 459d0df

podman:
podman version 3.4.2

runc:
runc version 1.0.2
```

## Step

upgrade dragonfly deployment with the following config to enable ingress of manager 

```yaml
manager:
  ingress:
    # -- Enable ingress
    enable: true
    # -- Ingress annotations
    annotations: {}
    # -- Ingress host path
    path: /
    # -- Manager ingress hosts
    hosts: []
    # -- Ingress TLS configuration
    tls: []
```

get error information:

```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1" 
```
